services:
  lunkvayapi:
    image: flakooooo/lunkvay-api:latest
    ports:
      - "8080:8080"
    volumes:
      - ./Media:/app/Media
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - MEDIA_ROOT=/app/Media
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: flako
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: lunkvaydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flako -d lunkvaydb"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
