services:
  lunkvayapi:
    image: ${DOCKER_REGISTRY-}lunkvayapi
    build:
      context: .
      dockerfile: mainapi/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
