services:
  lunkvayapi:
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}

  postgres:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flako -d lunkvaydb"]
      interval: 5s
      timeout: 5s
      retries: 10
