services:
  lunkvayapi:
    image: ${DOCKER_REGISTRY-}lunkvayapi
    build:
      context: .
      dockerfile: mainapi/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./Media:/app/Media
    environment:
      - MEDIA_ROOT=/app/Media
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: flako
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: lunkvaydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
